//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Bazaar.Infrastructure.CrossCutting.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Configs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PM.Bazaar.Infrastructure.CrossCutting.Configuration.Configs", typeof(Configs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /default_avatar.png.
        /// </summary>
        public static string DefaultAvatarUrl {
            get {
                return ResourceManager.GetString("DefaultAvatarUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        public static string MaxCharactersDescriptionAd {
            get {
                return ResourceManager.GetString("MaxCharactersDescriptionAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        public static string MaxCharactersEmail {
            get {
                return ResourceManager.GetString("MaxCharactersEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string MaxCharactersLastName {
            get {
                return ResourceManager.GetString("MaxCharactersLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string MaxCharactersName {
            get {
                return ResourceManager.GetString("MaxCharactersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string MaxCharactersPassword {
            get {
                return ResourceManager.GetString("MaxCharactersPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        public static string MaxCharactersQuestion {
            get {
                return ResourceManager.GetString("MaxCharactersQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        public static string MaxCharactersTitleAd {
            get {
                return ResourceManager.GetString("MaxCharactersTitleAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string MaxHeightAvatar {
            get {
                return ResourceManager.GetString("MaxHeightAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 768.
        /// </summary>
        public static string MaxHeightPictureAd {
            get {
                return ResourceManager.GetString("MaxHeightPictureAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2048.
        /// </summary>
        public static string MaxPictureLength {
            get {
                return ResourceManager.GetString("MaxPictureLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MaxPicturesAd {
            get {
                return ResourceManager.GetString("MaxPicturesAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string MaxProductPrice {
            get {
                return ResourceManager.GetString("MaxProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string MaxWidthAvatar {
            get {
                return ResourceManager.GetString("MaxWidthAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280.
        /// </summary>
        public static string MaxWidthPictureAd {
            get {
                return ResourceManager.GetString("MaxWidthPictureAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string MinCharactersDescriptionAd {
            get {
                return ResourceManager.GetString("MinCharactersDescriptionAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string MinCharactersEmail {
            get {
                return ResourceManager.GetString("MinCharactersEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MinCharactersLastName {
            get {
                return ResourceManager.GetString("MinCharactersLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MinCharactersName {
            get {
                return ResourceManager.GetString("MinCharactersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string MinCharactersPassword {
            get {
                return ResourceManager.GetString("MinCharactersPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MinCharactersQuestion {
            get {
                return ResourceManager.GetString("MinCharactersQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MinCharactersTitleAd {
            get {
                return ResourceManager.GetString("MinCharactersTitleAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string MinPicturesAd {
            get {
                return ResourceManager.GetString("MinPicturesAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MinProductPrice {
            get {
                return ResourceManager.GetString("MinProductPrice", resourceCulture);
            }
        }
    }
}
